# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shivam Garg
email: sgdpsi@gmail.com
email2: sgarg2@ualberta.ca
description: > # this means to ignore newlines until "baseurl:"
  Homepage of Shivam Garg, UAlberta
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://svmgrg.github.io/" # the base hostname & protocol for your site

github_username:  svmgrg

# Build settings
markdown: kramdown
